#!/bin/bash
set -eo pipefail

if [ -f ./setup ]
then
  source ./setup
fi

echo "Launching elasticsearch instance..."
su-exec elastico /usr/share/elasticsearch/bin/elasticsearch -Epath.conf=/etc/elasticsearch
