FROM ghcr.io/dockhippie/alpine:latest-amd64@sha256:3b0f6fcc3740af39ade20df4e15f3221cd3359a582157724ff1b70c34ad7f9f8

EXPOSE 9200 9300

VOLUME ["/var/lib/elasticsearch", "/etc/elasticsearch/jvm.options.d"]
WORKDIR /var/lib/elasticsearch
CMD ["/usr/bin/container"]

# renovate: datasource=github-releases depName=elastic/elasticsearch
ENV ELASTICSEARCH_VERSION=8.3.3

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/elasticsearch && \
  groupadd -g 1000 elastico && \
  useradd -u 1000 -d /var/lib/elasticsearch -g elastico -s /bin/bash -M elastico && \
  apk add coreutils java-jna-native openjdk17-jre && \
  rm -rf /var/cache/apk/*

RUN mkdir -p /usr/share/elasticsearch && \
  curl -sLo - https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ELASTICSEARCH_VERSION}-linux-x86_64.tar.gz | tar xvzf - --strip 1 --exclude jdk --exclude config --exclude logs --exclude plugins --exclude LICENSE.txt --exclude NOTICE.txt --exclude README.asciidoc --exclude bin/*.bat --exclude bin/*.exe --exclude modules/x-pack-ml -C /usr/share/elasticsearch && \
  ln -sf /usr/share/elasticsearch/bin/elasticsearch* /usr/bin/ && \
  ln -sf /usr/share/elasticsearch/bin/xpack* /usr/bin/ && \
  ln -sf /var/lib/elasticsearch/plugins /usr/share/elasticsearch/plugins && \
  chown elastico:elastico /usr/share/elasticsearch

COPY ./overlay /

RUN find /etc/container.d /etc/entrypoint.d -type f -name \*.sh -exec sed -i 's/\r$//' {} +; \
  sed -i 's/\r$//' /usr/bin/healthcheck /usr/bin/container && \
  chmod +x /usr/bin/healthcheck /usr/bin/container /etc/container.d/*.sh /etc/entrypoint.d/*.sh
