#!/usr/bin/env bash

declare -x ELASTICSEARCH_BASE_DIR
: "${ELASTICSEARCH_BASE_DIR:="/var/lib/elasticsearch"}"

declare -x ELASTICSEARCH_CONFIG_DIR
: "${ELASTICSEARCH_CONFIG_DIR:="/etc/elasticsearch"}"

declare -x ELASTICSEARCH_DATA_DIR
: "${ELASTICSEARCH_DATA_DIR:="${ELASTICSEARCH_BASE_DIR}/data"}"

declare -x ELASTICSEARCH_LOGS_DIR
: "${ELASTICSEARCH_LOGS_DIR:="${ELASTICSEARCH_BASE_DIR}/logs"}"

declare -x ELASTICSEARCH_PLUGINS_DIR
: "${ELASTICSEARCH_PLUGINS_DIR:="${ELASTICSEARCH_BASE_DIR}/plugins"}"

declare -x ELASTICSEARCH_SCRIPTS_DIR
: "${ELASTICSEARCH_SCRIPTS_DIR:="${ELASTICSEARCH_BASE_DIR}/scripts"}"

declare -x ELASTICSEARCH_WORK_DIR
: "${ELASTICSEARCH_WORK_DIR:="${ELASTICSEARCH_BASE_DIR}/work"}"

declare -x ELASTICSEARCH_SKIP_TEMPLATES
: "${ELASTICSEARCH_SKIP_TEMPLATES:="${ELASTICSEARCH_BASE_DIR}/work"}"

