FROM ghcr.io/dockhippie/alpine:latest-arm64@sha256:f2b5f17d5bcecc876889c72fe2f08c8747a6643a250ccd7b5b72ccdfddbb36f7

EXPOSE 9200 9300

VOLUME ["/var/lib/elasticsearch"]
WORKDIR /var/lib/elasticsearch
CMD ["/usr/bin/container"]

# renovate: datasource=github-releases depName=elastic/elasticsearch
ENV ELASTICSEARCH_VERSION=6.4.3

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/elasticsearch && \
  groupadd -g 1000 elastico && \
  useradd -u 1000 -d /var/lib/elasticsearch -g elastico -s /bin/bash -M elastico && \
  apk add coreutils java-jna-native openjdk8-jre && \
  rm -rf /var/cache/apk/*

RUN mkdir -p /usr/share/elasticsearch && \
  curl -sLo - https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ELASTICSEARCH_VERSION}.tar.gz | tar xvzf - --strip 1 --exclude config --exclude logs --exclude plugins --exclude LICENSE.txt --exclude NOTICE.txt --exclude README.textile --exclude bin/*.bat --exclude bin/*.exe --exclude modules/x-pack-ml -C /usr/share/elasticsearch && \
  ln -sf /usr/share/elasticsearch/bin/elasticsearch* /usr/bin/ && \
  ln -sf /usr/share/elasticsearch/bin/xpack* /usr/bin/ && \
  ln -sf /var/lib/elasticsearch/plugins /usr/share/elasticsearch/plugins && \
  chown elastico:elastico /usr/share/elasticsearch

COPY ./overlay /

RUN find /etc/container.d /etc/entrypoint.d -type f -name \*.sh -exec sed -i 's/\r$//' {} +; \
  sed -i 's/\r$//' /usr/bin/healthcheck /usr/bin/container && \
  chmod +x /usr/bin/healthcheck /usr/bin/container /etc/container.d/*.sh /etc/entrypoint.d/*.sh
