FROM ghcr.io/dockhippie/alpine:latest-arm64@sha256:70de2c5b48566c06e31a28c2f0987ae0d36d284035f97da49fbc715d4ed401c1

EXPOSE 9200 9300

VOLUME ["/var/lib/elasticsearch"]
WORKDIR /var/lib/elasticsearch
CMD ["/usr/bin/container"]

# renovate: datasource=github-releases depName=elastic/elasticsearch
ENV ELASTICSEARCH_VERSION=5.6.16

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/elasticsearch && \
  groupadd -g 1000 elastico && \
  useradd -u 1000 -d /var/lib/elasticsearch -g elastico -s /bin/bash -M elastico && \
  apk add coreutils java-jna-native openjdk8-jre && \
  rm -rf /var/cache/apk/*

RUN mkdir -p /usr/share/elasticsearch && \
  curl -sLo - https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ELASTICSEARCH_VERSION}.tar.gz | tar xvzf - --strip 1 --exclude config --exclude logs --exclude plugins --exclude LICENSE.txt --exclude NOTICE.txt --exclude README.textile --exclude bin/*.bat --exclude bin/*.exe -C /usr/share/elasticsearch && \
  ln -sf /usr/share/elasticsearch/bin/elasticsearch* /usr/bin/ && \
  ln -sf /var/lib/elasticsearch/plugins /usr/share/elasticsearch/plugins && \
  chown elastico:elastico /usr/share/elasticsearch

COPY ./overlay /
