#!/usr/bin/env bash

declare -x ELASTICSEARCH_HEALTHCHECK_URL
[[ -z "${ELASTICSEARCH_HEALTHCHECK_URL}" ]] && ELASTICSEARCH_HEALTHCHECK_URL="http://localhost:9200/"

declare -x ELASTICSEARCH_HEALTHCHECK_CODE
[[ -z "${ELASTICSEARCH_HEALTHCHECK_CODE}" ]] && ELASTICSEARCH_HEALTHCHECK_CODE="200"

true
